export const articles={
ko:[
{slug:"exam-overview",category:"시험 안내",title:"컴퓨터활용능력 2급 시험 구조",description:"필기 40문항·40분과 스프레드시트 실기 40분을 한 흐름으로 준비합니다.",sections:[["두 시험의 역할을 구분하세요","필기는 컴퓨터 일반과 스프레드시트 일반 2과목에서 객관식 40문항을 40분 동안 풉니다. 실기는 스프레드시트 실무를 40분 동안 컴퓨터 작업형으로 수행합니다."],["합격 기준을 먼저 계산하세요","필기는 각 과목 40점 이상이면서 전체 평균 60점 이상이어야 합니다. 실기는 100점 만점에 70점 이상이 기준입니다."],["필기와 실기를 너무 늦게 분리하지 마세요","필기 개념을 Excel 화면과 연결하면 함수, 참조, 데이터 기능을 더 오래 기억할 수 있습니다. 필기 합격 뒤 처음 프로그램을 여는 일정은 피하세요."],["적용 출제기준을 확인하세요","2026년에는 2024~2026 출제기준이 적용됩니다. 대한상공회의소는 2027년 1월 1일부터 적용할 2027~2029 기준도 게시했습니다."]]},
{slug:"written-strategy",category:"필기",title:"40문항을 40분에 푸는 방법",description:"과락을 막고 검토 시간을 확보하는 2과목 필기 운영법입니다.",sections:[["한 문제에 오래 멈추지 마세요","확실한 문제를 먼저 풀고 계산이나 세부 기능 비교가 필요한 문제를 표시합니다. 마지막 검토 시간을 따로 남겨야 지문 오독을 줄일 수 있습니다."],["두 과목 점수를 따로 기록하세요","평균이 높아도 한 과목이 40점 미만이면 불합격입니다. 모의고사 결과를 컴퓨터 일반과 스프레드시트 일반로 나눠 기록하세요."],["오답을 원인별로 분류하세요","개념 부족, 용어 혼동, 지문 오독, 시간 압박으로 나누면 다음 학습 행동이 명확해집니다. 답만 외우는 복습은 변형 문제에 약합니다."],["상시검정 문제를 복제한다고 믿지 마세요","대한상공회의소는 상시검정 문제를 문제은행 방식으로 운영하며 공개하지 않는다고 안내합니다. 연습문제는 출제기준을 익히는 독립 자료로 사용하세요."]]},
{slug:"computer-general",category:"필기",title:"컴퓨터 일반 핵심 개념 연결법",description:"운영체제·하드웨어·네트워크·보안을 기능과 목적 중심으로 정리합니다.",sections:[["이름보다 해결하는 문제를 보세요","운영체제 기능, 기억장치, 파일 시스템과 네트워크 장비를 무엇을 해결하는지 연결하면 비슷한 선택지를 구분하기 쉽습니다."],["단위는 직접 변환하세요","저장 용량과 전송 속도는 기준 단위를 먼저 쓰고 변환합니다. 계산 뒤 값의 크기가 현실적인지도 확인하세요."],["보안은 위협과 통제를 짝지으세요","악성코드, 피싱, 접근통제, 암호화와 백업을 예방-탐지-복구 흐름으로 정리하면 사례형 문제에 강해집니다."],["시험 환경을 기준으로 공부하세요","현재 안내는 Windows 10 공통 기능과 Office LTSC Professional Plus 2021을 기준으로 합니다. 화면 위치뿐 아니라 기능의 의미를 익히세요."]]},
{slug:"spreadsheet-theory",category:"필기",title:"스프레드시트 일반 필기 정리",description:"셀 참조·함수·차트·데이터 기능을 결과 중심으로 비교합니다.",sections:[["참조가 복사될 때를 그려보세요","상대·절대·혼합 참조가 행과 열 방향으로 어떻게 변하는지 작은 표에서 직접 확인합니다. 기호 위치만 외우면 복합 수식에서 흔들립니다."],["함수는 입력과 출력으로 묶으세요","조건, 날짜, 텍스트, 통계, 조회 함수의 입력값과 반환값을 비교합니다. 빈 셀과 오류 값이 있을 때의 차이도 확인하세요."],["데이터 기능은 전제 조건이 중요합니다","정렬, 필터, 부분합, 피벗과 유효성 검사는 헤더, 범위, 빈 행과 조건 위치가 결과를 바꿉니다."],["차트는 전달 목적부터 정하세요","비교, 추세, 구성비 중 무엇을 보여줄지 결정한 뒤 차트 종류, 축, 계열과 범례를 선택합니다."]]},
{slug:"office-environment",category:"실기",title:"Office LTSC 2021 실기 환경 준비",description:"버전 차이로 생기는 메뉴·함수·저장 방식의 혼란을 줄입니다.",sections:[["공식 대상 프로그램을 확인하세요","2024~2026 컴퓨터활용능력 실기는 Microsoft Office LTSC Professional Plus 2021을 사용합니다. 개인 연습 환경의 버전과 차이를 파악하세요."],["버튼 위치보다 명령 목적을 익히세요","버전이나 창 크기에 따라 리본 위치가 달라질 수 있습니다. 명령 이름, 옵션과 예상 결과를 말로 설명할 수 있어야 합니다."],["외부 도구를 전제로 연습하지 마세요","공식 안내는 Windows 계산기와 메모장 기능을 사용할 수 없다고 명시합니다. 허용된 방식 안에서 중간 계산과 확인을 처리하세요."],["저장 습관을 고정하세요","시작할 때 파일명과 위치를 확인하고 큰 작업이 끝날 때 저장합니다. 제출 방식과 원본 파일 처리 규칙은 시험장 안내를 따르세요."]]},
{slug:"functions-formulas",category:"실기",title:"함수와 수식 작업의 검증 순서",description:"수식을 한 셀에서 검증한 뒤 안전하게 확장하는 방법입니다.",sections:[["조건을 자연어로 먼저 쓰세요","중첩 함수부터 입력하지 말고 어떤 조건에서 어떤 값을 반환해야 하는지 짧은 문장으로 정리합니다."],["참조를 색으로 구분하세요","변해야 하는 셀과 고정해야 하는 범위를 구분한 뒤 상대·절대·혼합 참조를 선택합니다."],["경계값을 확인하세요","조건의 바로 아래와 위, 빈 셀, 오류 값, 동률처럼 결과가 바뀌는 지점을 테스트해야 수식이 안정적입니다."],["확인한 뒤 채우세요","첫 셀의 결과와 참조를 확인한 후 복사하고, 범위 시작과 끝 셀을 다시 검사합니다."]]},
{slug:"data-analysis",category:"실기",title:"정렬·필터·피벗·차트 작업",description:"원본 범위를 보호하면서 분석 결과를 정확한 위치에 만드는 순서입니다.",sections:[["원본 범위와 헤더를 먼저 확인하세요","빈 행, 병합 셀, 잘못된 헤더 선택은 분석 결과를 바꿉니다. 작업 전에 범위의 시작과 끝을 표시하세요."],["조건 범위를 분리하세요","고급 필터나 데이터베이스 함수는 조건 제목과 입력 위치가 중요합니다. 결과가 비어 있다면 조건 범위부터 확인하세요."],["피벗은 필드 역할을 나누세요","행, 열, 값, 필터 영역에 어떤 필드를 둘지 문제의 요구 결과에서 역으로 결정합니다."],["차트는 데이터와 표시를 모두 검토하세요","원본 계열, 범주, 축과 제목이 요구사항과 맞는지 확인합니다. 모양이 비슷하다고 작업을 끝내지 마세요."]]},
{slug:"practical-workflow",category:"실기",title:"40분 스프레드시트 실기 운영",description:"작업 의존성·확실한 점수·오류 복구를 고려한 시간제한 전략입니다.",sections:[["전체 문제를 먼저 훑으세요","다음 작업이 앞의 결과를 참조하는지 확인합니다. 서로 독립적인 작업은 확실성과 소요 시간에 따라 순서를 조정할 수 있습니다."],["확실한 작업을 먼저 완성하세요","초반에 안정적인 점수를 확보하면 어려운 함수나 분석 작업에서 시간을 더 유연하게 쓸 수 있습니다."],["오류에 표시하고 이동하세요","한 오류에 오래 머물지 말고 위치와 증상을 표시한 뒤 다음 작업으로 넘어갑니다. 마지막 검토 시간에 원인을 좁히세요."],["마지막 3분은 제출 상태를 봅니다","수식 결과, 범위, 차트, 인쇄·서식 요구와 파일 저장 상태를 확인하고 시험장 안내에 따라 제출합니다."]]},
{slug:"passing-validity",category:"합격·접수",title:"과락·70점·필기 유효기간",description:"필기 이중 기준과 실기 70점, 합격 후 2년 일정을 정확히 관리합니다.",sections:[["필기는 두 조건을 모두 만족해야 합니다","컴퓨터 일반과 스프레드시트 일반이 각각 40점 이상이고 전체 평균이 60점 이상이어야 합니다."],["실기는 70점 이상입니다","스프레드시트 작업형에서 100점 만점 중 70점 이상이 합격 기준입니다. 연습에서는 한 번의 70점보다 반복해서 기준을 넘는 안정성을 봅니다."],["필기 합격은 2년간 유효합니다","공식 FAQ는 필기 합격발표일 기준 만 2년이라고 안내합니다. 정확한 만료일은 대한상공회의소 마이페이지에서 확인하세요."],["실기 시험일이 기간 안에 있어야 합니다","합격자 발표가 이후여도 실기 시험일이 필기 유효기간 안이면 응시할 수 있다고 공식 FAQ가 설명합니다."]]},
{slug:"six-week-plan",category:"학습 계획",title:"필기·실기 6주 학습 계획",description:"개념과 Excel 작업을 같은 주에 연결해 실기 시작을 늦추지 않습니다.",sections:[["1주: 시험 지도 만들기","공식 출제기준을 읽고 컴퓨터 일반과 스프레드시트 일반의 큰 영역을 정리합니다. Excel 파일·시트·셀·리본 구조도 함께 익힙니다."],["2~3주: 개념과 짧은 작업","필기 문제를 풀고 해당 개념을 실제 셀, 함수, 정렬 또는 차트에서 확인합니다. 오답 원인을 기록하세요."],["4~5주: 시간 제한 연습","40분 필기 세트와 40분 실기 세트를 번갈아 수행합니다. 지식 부족과 조작 속도 문제를 구분해 보완합니다."],["6주: 안정성 점검","새 기능을 넓히기보다 자주 틀리는 참조, 조건, 범위와 저장 실수를 줄입니다. 예약 정보와 최신 응시 안내도 확인하세요."]]}
],
en:[
{slug:"exam-overview",category:"Exam",title:"Korean Computer Literacy Level 2 overview",description:"Prepare a 40-item written test and a separate 40-minute spreadsheet practical test.",sections:[["Understand the two formats","The written test has 40 multiple-choice questions across computer and spreadsheet fundamentals in 40 minutes. The practical test is a 40-minute spreadsheet computer task."],["Plan around both pass conditions","Written candidates need at least 40 in each subject and a 60 overall average. Practical candidates need at least 70 out of 100."],["Connect theory to the screen early","Link written concepts to Excel while preparing instead of opening the application for the first time after the written result."],["Check the applicable specification","The 2024–2026 specification applies in 2026. KCCI has published a 2027–2029 specification effective January 1, 2027."]]},
{slug:"written-strategy",category:"Written",title:"A 40-question written-test strategy",description:"Protect both subjects from the floor and preserve time for review.",sections:[["Do not stop on one item","Secure clear answers first, flag calculations or close comparisons, and preserve a final review block."],["Track the two subjects separately","A strong average cannot rescue a subject below 40. Record computer and spreadsheet scores independently."],["Tag the cause of each miss","Use missing knowledge, confused terms, misread wording and time pressure. Practise new examples with the same cause."],["Do not expect copied live items","KCCI states that continuous-test question-bank items are not published. Use independent practice to learn the specification."]]},
{slug:"computer-general",category:"Written",title:"Connect computer fundamentals",description:"Organise operating systems, hardware, networking and security by purpose.",sections:[["Ask what problem each feature solves","Pair operating-system features, memory, file systems and network devices with their practical purpose."],["Make unit conversions visible","Write the base unit before converting capacity or speed, then check whether the result is plausible."],["Pair threats and controls","Connect malware, phishing, access control, encryption and backup through prevention, detection and recovery."],["Use the current environment","Current guidance references Windows 10 common functions and Office LTSC Professional Plus 2021."]]},
{slug:"spreadsheet-theory",category:"Written",title:"Spreadsheet theory for the written test",description:"Compare references, functions, charts and data tools through their results.",sections:[["Draw reference movement","Use a small grid to see how relative, absolute and mixed references change when copied."],["Group functions by input and output","Compare logical, date, text, statistical and lookup functions, including blanks and error values."],["Check prerequisites for data tools","Sorting, filtering, subtotals, pivots and validation depend on headers, ranges and blank rows."],["Choose charts from the communication goal","Decide whether the task is comparison, trend or composition before choosing chart, axis and series."]]},
{slug:"office-environment",category:"Practical",title:"Prepare the Office LTSC 2021 environment",description:"Reduce surprises caused by menu, function and saving differences.",sections:[["Use the official target as reference","KCCI lists Microsoft Office LTSC Professional Plus 2021 for the 2024–2026 practical test."],["Learn command purpose","Ribbon position can change by edition or window size. Explain the command, its options and expected result."],["Do not depend on external utilities","Current guidance says Windows Calculator and Notepad cannot be used. Rehearse within permitted methods."],["Standardise saving","Confirm file name and location at the start and save after meaningful stages. Follow venue submission rules."]]},
{slug:"functions-formulas",category:"Practical",title:"Validate functions and formulas",description:"Prove one formula before safely extending it across the range.",sections:[["Write the condition in plain language","State what should be returned under each condition before nesting functions."],["Separate moving and fixed references","Identify which cells must move and which ranges stay fixed before choosing reference type."],["Test boundary cases","Check values just below and above a condition, blanks, errors and ties."],["Fill only after validation","Confirm the first result and references, then copy and inspect the first and last cells."]]},
{slug:"data-analysis",category:"Practical",title:"Sort, filter, pivot and chart safely",description:"Protect the source range while producing the requested analysis output.",sections:[["Confirm source range and headers","Blank rows, merged cells and wrong headers can change the result."],["Keep criteria ranges clear","Advanced filters and database functions depend on exact criteria headings and placement."],["Assign pivot field roles from the result","Work backward from the required output to rows, columns, values and filters."],["Review both data and display","Verify source series, categories, axes and titles instead of stopping when the chart looks similar."]]},
{slug:"practical-workflow",category:"Practical",title:"Run the 40-minute spreadsheet practical",description:"Use dependencies, secure points and recovery time to control the test.",sections:[["Scan for task dependencies","Identify work that later formulas or analysis depend on. Reorder independent tasks by certainty and time."],["Secure reliable work first","Early stable points leave more flexibility for difficult functions or analysis."],["Mark errors and move","Record the location and symptom, continue, then return with a narrower diagnosis."],["Use the final minutes for submission state","Check formulas, ranges, charts, requested formatting and saved file state."]]},
{slug:"passing-validity",category:"Scoring",title:"Subject floors, 70 points and validity",description:"Manage the dual written rule, practical score and two-year written-pass window.",sections:[["Written has two conditions","Both subjects need at least 40 and the combined average needs at least 60."],["Practical needs 70","The spreadsheet task test needs at least 70 out of 100. Look for consistency across several timed attempts."],["A written pass is valid for two years","KCCI's FAQ says two full years from the written pass announcement date."],["The practical test date must be inside","The result may be announced later, but the practical test date must fall within the valid window."]]},
{slug:"six-week-plan",category:"Plan",title:"A six-week written and practical plan",description:"Connect concepts and Excel work in the same week instead of delaying practical study.",sections:[["Week 1: map the test","Read the official specification and map computer and spreadsheet domains while learning the workbook interface."],["Weeks 2–3: concepts plus short tasks","Answer written questions, reproduce the concept in cells, functions, sorting or charts, and log error causes."],["Weeks 4–5: timed practice","Alternate 40-minute written and practical sets. Separate knowledge gaps from operating-speed problems."],["Week 6: stability","Reduce recurring reference, condition, range and saving errors. Recheck appointment and current candidate instructions."]]}
]};
